language: php
#dist: trusty
php:
#  - '5.4'
#  - '5.5'
  - '5.6'
#  - '7.0'
#  - '7.1'
#  - hhvm
#  - nightly
env:
  global:
    # - APP_HOST="iubar.it"
before_script:
  - composer install --no-interaction --dev    
script: phpunit
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
    on_success: change  # options: [always|never|change] default: changes
    on_failure: always  # options: [always|never|change] default: always

    
